package visual;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        jPanelMostrarAdmin.add(panelEliminarUsuarios, "panelEliminarUsuarios");
        jPanelMostrarAdmin.add(panelAgregarUsuarios, "panelAgregarUsuarios");
        jPanelMostrarAdmin.add(panelModificarUsuarios, "panelModificarUsuarios");
        jPanelMostrarAdmin.add(panelGestionarUsuarios, "panelGestionarUsuarios");
        jPanelMostrarAdmin.add(panelReporteVentas, "panelReporteVentas");
        jPanelMostrarAdmin.add(panelCerrarSesion, "panelCerrarSesion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMostrarAdmin = new javax.swing.JPanel();
        panelEliminarUsuarios = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        listMeseros = new javax.swing.JList<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtIngreseMeseroEliminar = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        btnEliminarMesero = new javax.swing.JButton();
        btnCancelarEliminacionMesero = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        txtContraseñaAdministrador = new javax.swing.JTextField();
        panelAgregarUsuarios = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        btnRegistroMesero = new javax.swing.JButton();
        btnCancelarRegistroMesero = new javax.swing.JButton();
        txtNombreNuevoMesero = new javax.swing.JTextField();
        txtApellidoNuevoMesero = new javax.swing.JTextField();
        txtUsuarioNuevoMesero = new javax.swing.JTextField();
        txtContraseñaNuevoMesero = new javax.swing.JTextField();
        txtConfirmarContraseñaNuevoMesero = new javax.swing.JTextField();
        txtTelefonoNuevomesero = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        listMeseroActualizados = new javax.swing.JList<>();
        panelModificarUsuarios = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        listDatosMeseros = new javax.swing.JList<>();
        jLabel49 = new javax.swing.JLabel();
        txtNombreMeseroModificar = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txtModificarTelefono = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        txtModificarContarseña = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        txtNuevaContraseñaModificada = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        txtConfirCotraseñModificada = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        txtModificarRol = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        btnEditarDatosMesero = new javax.swing.JButton();
        btnCancelarEdicionDatos = new javax.swing.JButton();
        panelGestionarUsuarios = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        listGestionMeseros = new javax.swing.JList<>();
        jLabel63 = new javax.swing.JLabel();
        txtNombreGestionMesero = new javax.swing.JTextField();
        txtGestionContraseñaMesero = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        btnSeleccionarMesero = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        panelReporteVentas = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        txtFechaFinal = new javax.swing.JTextField();
        jScrollPane18 = new javax.swing.JScrollPane();
        btnReporteVentas = new javax.swing.JList<>();
        jLabel83 = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        jLabel85 = new javax.swing.JLabel();
        btnVerReporte = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        txtGananciaReporteSeleccionado = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        txtFechaReporteSeleccionado = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        txtCantidadReporteSeleccionado = new javax.swing.JTextField();
        panelCerrarSesion = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtIngreseCodigoGenerado = new javax.swing.JTextField();
        btnCerrarSesionAdmnistrador = new javax.swing.JButton();
        txtCodigoGenerado = new javax.swing.JTextField();
        jMenuAdmin = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        menItemEliminarUsuario = new javax.swing.JMenuItem();
        menItemAgregarUsuario = new javax.swing.JMenuItem();
        menItemModificarUsuario = new javax.swing.JMenuItem();
        menItemGestionarUsuarios = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menItemReporteVentas = new javax.swing.JMenuItem();
        menuCerrar = new javax.swing.JMenu();
        menItemCerrarSecsion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMostrarAdmin.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanelMostrarAdmin.setLayout(new java.awt.CardLayout());

        panelEliminarUsuarios.setBackground(new java.awt.Color(153, 153, 153));
        panelEliminarUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEliminarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("ELIMINAR MESERO");
        panelEliminarUsuarios.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 24, -1, -1));

        listMeseros.setBackground(new java.awt.Color(255, 204, 51));
        jScrollPane7.setViewportView(listMeseros);

        panelEliminarUsuarios.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 110, 197, 336));

        jLabel30.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Lista de meseros :");
        panelEliminarUsuarios.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 73, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Ingrese nombre del mesero a eliminar :");
        panelEliminarUsuarios.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 128, -1, -1));
        panelEliminarUsuarios.add(txtIngreseMeseroEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 153, 224, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Desea eliminar al mesero ? ");
        panelEliminarUsuarios.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 308, -1, -1));

        btnEliminarMesero.setBackground(new java.awt.Color(0, 153, 0));
        btnEliminarMesero.setText("Confirmar");
        btnEliminarMesero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEliminarUsuarios.add(btnEliminarMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 346, 75, 30));

        btnCancelarEliminacionMesero.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelarEliminacionMesero.setText("Cancelar");
        btnCancelarEliminacionMesero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEliminarUsuarios.add(btnCancelarEliminacionMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 346, 59, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Confirmacion de contraseña : ");
        panelEliminarUsuarios.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 206, -1, -1));

        txtContraseñaAdministrador.setText("Contraseña del Administrador");
        panelEliminarUsuarios.add(txtContraseñaAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 237, 222, -1));

        jPanelMostrarAdmin.add(panelEliminarUsuarios, "card6");

        panelAgregarUsuarios.setBackground(new java.awt.Color(153, 153, 153));
        panelAgregarUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAgregarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("REGISTRO DE NUEVO MESERO");
        panelAgregarUsuarios.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 34, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Completa los sigueintes campos para el registro :");
        panelAgregarUsuarios.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 84, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Nombres : ");
        panelAgregarUsuarios.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 120, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Apellidos :");
        panelAgregarUsuarios.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 185, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Nombre de usuario : ");
        panelAgregarUsuarios.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 249, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Contraseña :");
        panelAgregarUsuarios.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 320, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Confirmacion de contraseña : ");
        panelAgregarUsuarios.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 120, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Telefono : ");
        panelAgregarUsuarios.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 185, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Desea registrar al mesero ? ");
        panelAgregarUsuarios.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 320, -1, -1));

        btnRegistroMesero.setBackground(new java.awt.Color(0, 153, 0));
        btnRegistroMesero.setText("Confirmar");
        btnRegistroMesero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAgregarUsuarios.add(btnRegistroMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 358, 72, 28));

        btnCancelarRegistroMesero.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelarRegistroMesero.setText("Cancelar");
        btnCancelarRegistroMesero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAgregarUsuarios.add(btnCancelarRegistroMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 358, 66, 28));
        panelAgregarUsuarios.add(txtNombreNuevoMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 151, 233, -1));
        panelAgregarUsuarios.add(txtApellidoNuevoMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 210, 233, -1));
        panelAgregarUsuarios.add(txtUsuarioNuevoMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 280, 233, -1));
        panelAgregarUsuarios.add(txtContraseñaNuevoMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 347, 233, -1));
        panelAgregarUsuarios.add(txtConfirmarContraseñaNuevoMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 151, 164, -1));
        panelAgregarUsuarios.add(txtTelefonoNuevomesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 210, 164, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Lista de meseros actualizada :");
        panelAgregarUsuarios.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 120, -1, -1));

        listMeseroActualizados.setBackground(new java.awt.Color(255, 204, 51));
        jScrollPane9.setViewportView(listMeseroActualizados);

        panelAgregarUsuarios.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 151, 188, 269));

        jPanelMostrarAdmin.add(panelAgregarUsuarios, "card7");

        panelModificarUsuarios.setBackground(new java.awt.Color(153, 153, 153));
        panelModificarUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelModificarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("EDITAR DATOS DEL MESERO");
        panelModificarUsuarios.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 28, -1, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Llene todos los campos para la actualizacion.");
        panelModificarUsuarios.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 66, -1, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Lista de los meseros :");
        panelModificarUsuarios.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 103, -1, -1));

        listDatosMeseros.setBackground(new java.awt.Color(255, 204, 51));
        jScrollPane10.setViewportView(listDatosMeseros);

        panelModificarUsuarios.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 128, 142, 290));

        jLabel49.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Ingrese nombre del mesero a modificar :");
        panelModificarUsuarios.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 128, -1, -1));
        panelModificarUsuarios.add(txtNombreMeseroModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 153, 178, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Modificacion de los datos :");
        panelModificarUsuarios.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 181, -1, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("Telefono : ");
        panelModificarUsuarios.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 212, -1, -1));
        panelModificarUsuarios.add(txtModificarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 237, 164, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("Contraseña Anterior :");
        panelModificarUsuarios.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 324, -1, -1));
        panelModificarUsuarios.add(txtModificarContarseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 349, 218, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Nueva contarseña : ");
        panelModificarUsuarios.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 212, -1, -1));
        panelModificarUsuarios.add(txtNuevaContraseñaModificada, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 237, 218, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("Confirmar contraseña : ");
        panelModificarUsuarios.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 271, -1, -1));
        panelModificarUsuarios.add(txtConfirCotraseñModificada, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 296, 218, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("Rol : ");
        panelModificarUsuarios.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 271, -1, -1));
        panelModificarUsuarios.add(txtModificarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 296, 164, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("Desea guardar los cambios ?");
        panelModificarUsuarios.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 348, -1, -1));

        btnEditarDatosMesero.setBackground(new java.awt.Color(0, 153, 0));
        btnEditarDatosMesero.setText("Confirmar");
        btnEditarDatosMesero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelModificarUsuarios.add(btnEditarDatosMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 386, 66, 31));

        btnCancelarEdicionDatos.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelarEdicionDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarEdicionDatos.setText("Cancelar");
        btnCancelarEdicionDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelModificarUsuarios.add(btnCancelarEdicionDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 386, 61, 31));

        jPanelMostrarAdmin.add(panelModificarUsuarios, "card8");

        panelGestionarUsuarios.setBackground(new java.awt.Color(153, 153, 153));
        panelGestionarUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelGestionarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText("GESTION DE MESEROS");
        panelGestionarUsuarios.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 29, -1, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 0, 0));
        jLabel61.setText("Vista general de todos los meseros :");
        panelGestionarUsuarios.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 79, -1, 25));

        listGestionMeseros.setBackground(new java.awt.Color(255, 204, 51));
        jScrollPane12.setViewportView(listGestionMeseros);

        panelGestionarUsuarios.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 110, 157, 322));

        jLabel63.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 0, 0));
        jLabel63.setText("Nombre del mesero : ");
        panelGestionarUsuarios.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 208, -1, -1));
        panelGestionarUsuarios.add(txtNombreGestionMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 239, 154, -1));
        panelGestionarUsuarios.add(txtGestionContraseñaMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 298, 178, -1));

        jLabel70.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 0, 0));
        jLabel70.setText("Contraseña del mesero :");
        panelGestionarUsuarios.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 273, -1, -1));

        btnSeleccionarMesero.setBackground(new java.awt.Color(102, 153, 0));
        btnSeleccionarMesero.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnSeleccionarMesero.setText("Seleccione un mesero");
        btnSeleccionarMesero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelGestionarUsuarios.add(btnSeleccionarMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 247, 178, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Visualizacion del mesero seleccionado :");
        panelGestionarUsuarios.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 161, -1, -1));

        jPanelMostrarAdmin.add(panelGestionarUsuarios, "card9");

        panelReporteVentas.setBackground(new java.awt.Color(153, 153, 153));
        panelReporteVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelReporteVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel79.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(0, 0, 0));
        jLabel79.setText("REPORTE DE VENTAS");
        panelReporteVentas.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 24, 293, -1));

        jLabel80.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(0, 0, 0));
        jLabel80.setText("Rango de fecha para ver los reportes");
        panelReporteVentas.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel81.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(0, 0, 0));
        jLabel81.setText("Desde :");
        panelReporteVentas.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        panelReporteVentas.add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 158, -1));

        jLabel82.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 0, 0));
        jLabel82.setText("Hasta :");
        panelReporteVentas.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        panelReporteVentas.add(txtFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 158, -1));

        btnReporteVentas.setBackground(new java.awt.Color(255, 204, 51));
        jScrollPane18.setViewportView(btnReporteVentas);

        panelReporteVentas.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 206, 240));

        jLabel83.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(0, 0, 0));
        jLabel83.setText("Reportes encontrados");
        panelReporteVentas.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        btnGenerarReporte.setBackground(new java.awt.Color(102, 102, 0));
        btnGenerarReporte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerarReporte.setText("Buscar reportes");
        panelReporteVentas.add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 60));

        jLabel85.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(0, 0, 0));
        jLabel85.setText("Visualizacion del reporte seleccionado");
        panelReporteVentas.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        btnVerReporte.setBackground(new java.awt.Color(102, 102, 0));
        btnVerReporte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerReporte.setText("Ver reporte");
        panelReporteVentas.add(btnVerReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 110, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setText("Cantidad de productos vendidos");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 200, 30));
        jPanel1.add(txtGananciaReporteSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 150, 30));

        jLabel52.setText("Fecha del reporte");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 108, 30));
        jPanel1.add(txtFechaReporteSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 22, 150, 30));

        jLabel59.setText("Total ganancia");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));
        jPanel1.add(txtCantidadReporteSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 150, 30));

        panelReporteVentas.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 290, 280));

        jPanelMostrarAdmin.add(panelReporteVentas, "card11");

        panelCerrarSesion.setBackground(new java.awt.Color(102, 102, 102));
        panelCerrarSesion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel86.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(0, 0, 0));
        jLabel86.setText("CERRAR SESION");
        panelCerrarSesion.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 44, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Ingresar el codigo generado :");
        panelCerrarSesion.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 113, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Codigo generado :");
        panelCerrarSesion.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 150, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Ingresar codigo :");
        panelCerrarSesion.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 209, 136, -1));
        panelCerrarSesion.add(txtIngreseCodigoGenerado, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 233, 202, -1));

        btnCerrarSesionAdmnistrador.setBackground(new java.awt.Color(204, 0, 0));
        btnCerrarSesionAdmnistrador.setText("Cerrar sesion");
        btnCerrarSesionAdmnistrador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCerrarSesionAdmnistrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionAdmnistradorActionPerformed(evt);
            }
        });
        panelCerrarSesion.add(btnCerrarSesionAdmnistrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 175, 113, 64));

        txtCodigoGenerado.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        panelCerrarSesion.add(txtCodigoGenerado, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 175, 202, -1));

        jPanelMostrarAdmin.add(panelCerrarSesion, "card13");

        jMenuAdmin.setPreferredSize(new java.awt.Dimension(850, 51));

        menuUsuarios.setText("Usuarios");
        menuUsuarios.setPreferredSize(new java.awt.Dimension(122, 50));

        menItemEliminarUsuario.setText("Eliminar Usuario");
        menItemEliminarUsuario.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemEliminarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menItemEliminarUsuario);

        menItemAgregarUsuario.setText("Agregar Usuario");
        menItemAgregarUsuario.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemAgregarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menItemAgregarUsuario);

        menItemModificarUsuario.setText("Modificar Usuario");
        menItemModificarUsuario.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemModificarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menItemModificarUsuario);

        menItemGestionarUsuarios.setText("Gestionar Usuarios");
        menItemGestionarUsuarios.setPreferredSize(new java.awt.Dimension(180, 30));
        menItemGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemGestionarUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(menItemGestionarUsuarios);

        jMenuAdmin.add(menuUsuarios);

        menuReportes.setText("Reportes");
        menuReportes.setPreferredSize(new java.awt.Dimension(122, 50));

        menItemReporteVentas.setText("Reporte Ventas");
        menItemReporteVentas.setPreferredSize(new java.awt.Dimension(180, 30));
        menItemReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemReporteVentasActionPerformed(evt);
            }
        });
        menuReportes.add(menItemReporteVentas);

        jMenuAdmin.add(menuReportes);

        menuCerrar.setText("Cerrar");
        menuCerrar.setPreferredSize(new java.awt.Dimension(122, 50));

        menItemCerrarSecsion.setText("Cerrar Sesion");
        menItemCerrarSecsion.setPreferredSize(new java.awt.Dimension(180, 30));
        menItemCerrarSecsion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemCerrarSecsionActionPerformed(evt);
            }
        });
        menuCerrar.add(menItemCerrarSecsion);

        jMenuAdmin.add(menuCerrar);

        setJMenuBar(jMenuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelMostrarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMostrarAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menItemCerrarSecsionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemCerrarSecsionActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelCerrarSesion");
        int numeroCerrarSesion = (int)( Math.random()*90000) + 10000;
        txtCodigoGenerado.setText(String.valueOf(numeroCerrarSesion));
    }//GEN-LAST:event_menItemCerrarSecsionActionPerformed

    private void menItemReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemReporteVentasActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelReporteVentas");
    }//GEN-LAST:event_menItemReporteVentasActionPerformed

    private void menItemGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemGestionarUsuariosActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelGestionarUsuarios");
    }//GEN-LAST:event_menItemGestionarUsuariosActionPerformed

    private void menItemModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemModificarUsuarioActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelModificarUsuarios");
    }//GEN-LAST:event_menItemModificarUsuarioActionPerformed

    private void menItemAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemAgregarUsuarioActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelAgregarUsuarios");
    }//GEN-LAST:event_menItemAgregarUsuarioActionPerformed

    private void menItemEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemEliminarUsuarioActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelEliminarUsuarios");
    }//GEN-LAST:event_menItemEliminarUsuarioActionPerformed
    
    private void btnCerrarSesionAdmnistradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionAdmnistradorActionPerformed
        String numeroGenerado = txtCodigoGenerado.getText();
        String numeroIngresado = txtIngreseCodigoGenerado.getText();
        if (numeroIngresado.isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese el numero generado", "Error", JOptionPane.WARNING_MESSAGE);
        }else if(numeroGenerado.equalsIgnoreCase(numeroIngresado)){
            Object[] opciones = {"Si" , "No"};
            int seleccion = JOptionPane.showOptionDialog(
                    this,
                    "¿Seguro que quieres cerrar sesión?",
                    "Confirmación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    opciones,
                    opciones[0]
            );
            
            if (seleccion == JOptionPane.YES_OPTION)
            {
                new BievenidaO().setVisible(true);
                this.dispose();
            }
        }else
        {
            JOptionPane.showMessageDialog(rootPane, "Número ingresado incorrecto, Intentar otra vez." , "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCerrarSesionAdmnistradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEdicionDatos;
    private javax.swing.JButton btnCancelarEliminacionMesero;
    private javax.swing.JButton btnCancelarRegistroMesero;
    private javax.swing.JButton btnCerrarSesionAdmnistrador;
    private javax.swing.JButton btnEditarDatosMesero;
    private javax.swing.JButton btnEliminarMesero;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnRegistroMesero;
    private javax.swing.JList<String> btnReporteVentas;
    private javax.swing.JButton btnSeleccionarMesero;
    private javax.swing.JButton btnVerReporte;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JMenuBar jMenuAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMostrarAdmin;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList<String> listDatosMeseros;
    private javax.swing.JList<String> listGestionMeseros;
    private javax.swing.JList<String> listMeseroActualizados;
    private javax.swing.JList<String> listMeseros;
    private javax.swing.JMenuItem menItemAgregarUsuario;
    private javax.swing.JMenuItem menItemCerrarSecsion;
    private javax.swing.JMenuItem menItemEliminarUsuario;
    private javax.swing.JMenuItem menItemGestionarUsuarios;
    private javax.swing.JMenuItem menItemModificarUsuario;
    private javax.swing.JMenuItem menItemReporteVentas;
    private javax.swing.JMenu menuCerrar;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JPanel panelAgregarUsuarios;
    private javax.swing.JPanel panelCerrarSesion;
    private javax.swing.JPanel panelEliminarUsuarios;
    private javax.swing.JPanel panelGestionarUsuarios;
    private javax.swing.JPanel panelModificarUsuarios;
    private javax.swing.JPanel panelReporteVentas;
    private javax.swing.JTextField txtApellidoNuevoMesero;
    private javax.swing.JTextField txtCantidadReporteSeleccionado;
    private javax.swing.JTextField txtCodigoGenerado;
    private javax.swing.JTextField txtConfirCotraseñModificada;
    private javax.swing.JTextField txtConfirmarContraseñaNuevoMesero;
    private javax.swing.JTextField txtContraseñaAdministrador;
    private javax.swing.JTextField txtContraseñaNuevoMesero;
    private javax.swing.JTextField txtFechaFinal;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtFechaReporteSeleccionado;
    private javax.swing.JTextField txtGananciaReporteSeleccionado;
    private javax.swing.JTextField txtGestionContraseñaMesero;
    private javax.swing.JTextField txtIngreseCodigoGenerado;
    private javax.swing.JTextField txtIngreseMeseroEliminar;
    private javax.swing.JTextField txtModificarContarseña;
    private javax.swing.JTextField txtModificarRol;
    private javax.swing.JTextField txtModificarTelefono;
    private javax.swing.JTextField txtNombreGestionMesero;
    private javax.swing.JTextField txtNombreMeseroModificar;
    private javax.swing.JTextField txtNombreNuevoMesero;
    private javax.swing.JTextField txtNuevaContraseñaModificada;
    private javax.swing.JTextField txtTelefonoNuevomesero;
    private javax.swing.JTextField txtUsuarioNuevoMesero;
    // End of variables declaration//GEN-END:variables
}
