/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import java.awt.CardLayout;

/**
 *
 * @author DELL
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        //jPanelMostrarAdmin.add(panelEliminarProducto, "panelEliminarProducto");
        /*jPanelMostrarAdmin.add(panelAgregarProducto, "panelAgregarProducto");
        jPanelMostrarAdmin.add(panelProductosAgotados, "panelProductosAgotados");
        jPanelMostrarAdmin.add(panelProductosDisponilbes, "panelProductosDisponilbes");
        jPanelMostrarAdmin.add(panelEliminarUsuarios, "panelEliminarUsuarios");
        jPanelMostrarAdmin.add(panelAgregarUsuarios, "panelAgregarUsuarios");
        jPanelMostrarAdmin.add(panelModificarUsuarios, "panelModificarUsuarios");
        jPanelMostrarAdmin.add(panelGestionarsuarios, "panelGestionarsuarios");
        jPanelMostrarAdmin.add(panelAsignarPermisos, "panelAsignarPermisos");
        jPanelMostrarAdmin.add(panelReporteVentas, "panelReporteVentas");
        jPanelMostrarAdmin.add(panelVerHistorial, "panelVerHistorial");
        jPanelMostrarAdmin.add(panelCerrarSesion, "panelCerrarSesion");*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMostrarAdmin = new javax.swing.JPanel();
        jMenuAdmin = new javax.swing.JMenuBar();
        menuInventario = new javax.swing.JMenu();
        menItemEliminarProductos = new javax.swing.JMenuItem();
        menItemAgregarProductos = new javax.swing.JMenuItem();
        menuStock = new javax.swing.JMenu();
        menItemProductosAgotados = new javax.swing.JMenuItem();
        menItemProductosDisponibles = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menItemEliminarUsuario = new javax.swing.JMenuItem();
        menItemAgregarUsuario = new javax.swing.JMenuItem();
        menItemModificarUsuario = new javax.swing.JMenuItem();
        menItemGestionarUsuarios = new javax.swing.JMenuItem();
        menuPermisos = new javax.swing.JMenu();
        menItemAsignarPermisos = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menItemReporteVentas = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenu();
        menItemVerHistorial = new javax.swing.JMenuItem();
        menuCerrar = new javax.swing.JMenu();
        menItemCerrarSecsion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMostrarAdmin.setLayout(new java.awt.CardLayout());

        menuInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargarProductos.png"))); // NOI18N
        menuInventario.setText("Inventario");
        menuInventario.setPreferredSize(new java.awt.Dimension(122, 50));

        menItemEliminarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarProducto.png"))); // NOI18N
        menItemEliminarProductos.setText("Eliminar Producto");
        menItemEliminarProductos.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemEliminarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemEliminarProductosActionPerformed(evt);
            }
        });
        menuInventario.add(menItemEliminarProductos);

        menItemAgregarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productosDisponibles.png"))); // NOI18N
        menItemAgregarProductos.setText("Agregar Producto");
        menItemAgregarProductos.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemAgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemAgregarProductosActionPerformed(evt);
            }
        });
        menuInventario.add(menItemAgregarProductos);

        jMenuAdmin.add(menuInventario);

        menuStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar producto.png"))); // NOI18N
        menuStock.setText("Stock");
        menuStock.setPreferredSize(new java.awt.Dimension(122, 50));

        menItemProductosAgotados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agotado.png"))); // NOI18N
        menItemProductosAgotados.setText("Productos Agotados");
        menItemProductosAgotados.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemProductosAgotados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemProductosAgotadosActionPerformed(evt);
            }
        });
        menuStock.add(menItemProductosAgotados);

        menItemProductosDisponibles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productosDisponibles.png"))); // NOI18N
        menItemProductosDisponibles.setText("Productos Disponibles");
        menItemProductosDisponibles.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemProductosDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemProductosDisponiblesActionPerformed(evt);
            }
        });
        menuStock.add(menItemProductosDisponibles);

        jMenuAdmin.add(menuStock);

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N
        menuUsuarios.setText("Usuarios");
        menuUsuarios.setPreferredSize(new java.awt.Dimension(122, 50));

        menItemEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarProducto.png"))); // NOI18N
        menItemEliminarUsuario.setText("Eliminar Usuario");
        menItemEliminarUsuario.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemEliminarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menItemEliminarUsuario);

        menItemAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificarproducto.png"))); // NOI18N
        menItemAgregarUsuario.setText("Agregar Usuario");
        menItemAgregarUsuario.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemAgregarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menItemAgregarUsuario);

        menItemModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productosDisponibles.png"))); // NOI18N
        menItemModificarUsuario.setText("Modificar Usuario");
        menItemModificarUsuario.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemModificarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menItemModificarUsuario);

        menItemGestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion.png"))); // NOI18N
        menItemGestionarUsuarios.setText("Gestionar Usuarios");
        menItemGestionarUsuarios.setPreferredSize(new java.awt.Dimension(180, 30));
        menItemGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemGestionarUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(menItemGestionarUsuarios);

        jMenuAdmin.add(menuUsuarios);

        menuPermisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificarproducto.png"))); // NOI18N
        menuPermisos.setText("Permisos");
        menuPermisos.setPreferredSize(new java.awt.Dimension(180, 40));

        menItemAsignarPermisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productosDisponibles.png"))); // NOI18N
        menItemAsignarPermisos.setText("Asignar Permisos");
        menItemAsignarPermisos.setPreferredSize(new java.awt.Dimension(180, 30));
        menItemAsignarPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemAsignarPermisosActionPerformed(evt);
            }
        });
        menuPermisos.add(menItemAsignarPermisos);

        jMenuAdmin.add(menuPermisos);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargarProductos.png"))); // NOI18N
        menuReportes.setText("Reportes");
        menuReportes.setPreferredSize(new java.awt.Dimension(180, 40));

        menItemReporteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productosDisponibles.png"))); // NOI18N
        menItemReporteVentas.setText("Reporte Ventas");
        menItemReporteVentas.setPreferredSize(new java.awt.Dimension(180, 30));
        menItemReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemReporteVentasActionPerformed(evt);
            }
        });
        menuReportes.add(menItemReporteVentas);

        jMenuAdmin.add(menuReportes);

        menuHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificarproducto.png"))); // NOI18N
        menuHistorial.setText("Historial");
        menuHistorial.setPreferredSize(new java.awt.Dimension(180, 40));

        menItemVerHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productosDisponibles.png"))); // NOI18N
        menItemVerHistorial.setText("Ver  Historial");
        menItemVerHistorial.setPreferredSize(new java.awt.Dimension(180, 30));
        menItemVerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemVerHistorialActionPerformed(evt);
            }
        });
        menuHistorial.add(menItemVerHistorial);

        jMenuAdmin.add(menuHistorial);

        menuCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar sesion.png"))); // NOI18N
        menuCerrar.setText("Cerrar");
        menuCerrar.setPreferredSize(new java.awt.Dimension(180, 40));

        menItemCerrarSecsion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar sesion.png"))); // NOI18N
        menItemCerrarSecsion.setText("Cerrar Sesion");
        menItemCerrarSecsion.setPreferredSize(new java.awt.Dimension(180, 30));
        menItemCerrarSecsion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemCerrarSecsionActionPerformed(evt);
            }
        });
        menuCerrar.add(menItemCerrarSecsion);

        jMenuAdmin.add(menuCerrar);

        setJMenuBar(jMenuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanelMostrarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1041, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanelMostrarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menItemCerrarSecsionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemCerrarSecsionActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelCerrarSesion");
    }//GEN-LAST:event_menItemCerrarSecsionActionPerformed

    private void menItemEliminarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemEliminarProductosActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelEliminarProducto");
    }//GEN-LAST:event_menItemEliminarProductosActionPerformed

    private void menItemReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemReporteVentasActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelReporteVentas");
    }//GEN-LAST:event_menItemReporteVentasActionPerformed

    private void menItemAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemAgregarProductosActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelAgregarProducto");
    }//GEN-LAST:event_menItemAgregarProductosActionPerformed

    private void menItemProductosAgotadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemProductosAgotadosActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelProductosAgotados");
    }//GEN-LAST:event_menItemProductosAgotadosActionPerformed

    private void menItemProductosDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemProductosDisponiblesActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelProductosDisponilbes");
    }//GEN-LAST:event_menItemProductosDisponiblesActionPerformed

    private void menItemEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemEliminarUsuarioActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelEliminarUsuarios");
    }//GEN-LAST:event_menItemEliminarUsuarioActionPerformed

    private void menItemAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemAgregarUsuarioActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelAgregarUsuarios");
    }//GEN-LAST:event_menItemAgregarUsuarioActionPerformed

    private void menItemModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemModificarUsuarioActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelModificarUsuarios");
    }//GEN-LAST:event_menItemModificarUsuarioActionPerformed

    private void menItemGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemGestionarUsuariosActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelGestionarsuarios");
    }//GEN-LAST:event_menItemGestionarUsuariosActionPerformed

    private void menItemAsignarPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemAsignarPermisosActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelAsignarPermisos");
    }//GEN-LAST:event_menItemAsignarPermisosActionPerformed

    private void menItemVerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemVerHistorialActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrarAdmin.getLayout();
        layout.show(jPanelMostrarAdmin, "panelVerHistorial");
    }//GEN-LAST:event_menItemVerHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuAdmin;
    private javax.swing.JPanel jPanelMostrarAdmin;
    private javax.swing.JMenuItem menItemAgregarProductos;
    private javax.swing.JMenuItem menItemAgregarUsuario;
    private javax.swing.JMenuItem menItemAsignarPermisos;
    private javax.swing.JMenuItem menItemCerrarSecsion;
    private javax.swing.JMenuItem menItemEliminarProductos;
    private javax.swing.JMenuItem menItemEliminarUsuario;
    private javax.swing.JMenuItem menItemGestionarUsuarios;
    private javax.swing.JMenuItem menItemModificarUsuario;
    private javax.swing.JMenuItem menItemProductosAgotados;
    private javax.swing.JMenuItem menItemProductosDisponibles;
    private javax.swing.JMenuItem menItemReporteVentas;
    private javax.swing.JMenuItem menItemVerHistorial;
    private javax.swing.JMenu menuCerrar;
    private javax.swing.JMenu menuHistorial;
    private javax.swing.JMenu menuInventario;
    private javax.swing.JMenu menuPermisos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuStock;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
