/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import javax.swing.JOptionPane;

/**
 *
 * @author EQUIPO
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuarioIniciarSesion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtContraseniaIniciarSesion = new javax.swing.JTextField();
        btnIngresarInicioSesion = new javax.swing.JButton();
        btnCambiarNombreUsuario = new javax.swing.JButton();
        btnCambiarContrasenia = new javax.swing.JButton();
        btnVolverAtrasInicioSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreUsuario.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreUsuario.setText("Nombre de usuario");
        jPanel1.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 121, 26));

        txtNombreUsuarioIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreUsuarioIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 315, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 121, 26));
        jPanel1.add(txtContraseniaIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 315, -1));

        btnIngresarInicioSesion.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        btnIngresarInicioSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarInicioSesion.setText("Ingresar");
        btnIngresarInicioSesion.setToolTipText("");
        btnIngresarInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarInicioSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, 30));

        btnCambiarNombreUsuario.setBackground(new java.awt.Color(204, 204, 204));
        btnCambiarNombreUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCambiarNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiarNombreUsuario.setText("Cambiar nombre de usuario");
        btnCambiarNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarNombreUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        btnCambiarContrasenia.setBackground(new java.awt.Color(204, 204, 204));
        btnCambiarContrasenia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCambiarContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiarContrasenia.setText("Cambiar contraseña");
        btnCambiarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContraseniaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 186, -1));

        btnVolverAtrasInicioSesion.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        btnVolverAtrasInicioSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverAtrasInicioSesion.setText("Volver atras");
        btnVolverAtrasInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasInicioSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverAtrasInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, 54));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INICIO DE SESIÓN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioIniciarSesionActionPerformed

    private void btnVolverAtrasInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasInicioSesionActionPerformed
        new BievenidaO().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasInicioSesionActionPerformed

    private void btnIngresarInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarInicioSesionActionPerformed
        if (txtNombreUsuarioIniciarSesion.getText().equals("administrador" )&& txtContraseniaIniciarSesion.getText().equals("administrador")) {
            new Administrador().setVisible(true);
            this.dispose();
        }else if (txtNombreUsuarioIniciarSesion.getText().equals("mesero") && txtContraseniaIniciarSesion.getText().equals("mesero")) {
            new Mesero().setVisible(true);
            this.dispose();
        }else {
        // Opcional: mostrar un mensaje de error si las credenciales no son válidas
            JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrectos", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnIngresarInicioSesionActionPerformed

    private void btnCambiarNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarNombreUsuarioActionPerformed
        new CambioDeUsuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCambiarNombreUsuarioActionPerformed

    private void btnCambiarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContraseniaActionPerformed
        new CambiarContraseña().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCambiarContraseniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarContrasenia;
    private javax.swing.JButton btnCambiarNombreUsuario;
    private javax.swing.JButton btnIngresarInicioSesion;
    private javax.swing.JButton btnVolverAtrasInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JTextField txtContraseniaIniciarSesion;
    private javax.swing.JTextField txtNombreUsuarioIniciarSesion;
    // End of variables declaration//GEN-END:variables
}
