
package visual;

import java.awt.CardLayout;

/**
 *
 * @author EQUIPO
 */
public class Mesero extends javax.swing.JFrame {

    /**
     * Creates new form Mesero
     */
    public Mesero() {
        initComponents();
        jPanelMostrar.add(panelCargarMesas, "panelCargarMesas");
        jPanelMostrar.add(panelCargarProductos, "panelCargarProductos");
        jPanelMostrar.add(panelCerrarSesion, "panelCerrarSesion");
        jPanelMostrar.add(panelGestionarMesas, "panelGestionarMesas");
        jPanelMostrar.add(panelModProducto, "panelModProducto");
        jPanelMostrar.add(panelElimProducto, "panelElimProducto");
        jPanelMostrar.add(panelBuscProducto, "panelBuscProducto");
        jPanelMostrar.add(panelGenerarRecibo, "panelGenerarRecibo");
        jPanelMostrar.add(panelProducAgotados, "panelProducAgotados");
        jPanelMostrar.add(panelProducDisponibles, "panelProducDisponibles");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMostrar = new javax.swing.JPanel();
        panelCargarProductos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarRutaProductos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRutaPrductos = new javax.swing.JTextField();
        txtEstadoArchivoProductos = new javax.swing.JTextField();
        btnCargarProductos = new javax.swing.JButton();
        panelCerrarSesion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtIngresarCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoGenerado = new javax.swing.JTextField();
        btnComprobarCodigo = new javax.swing.JButton();
        panelGestionarMesas = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnMesa1 = new javax.swing.JButton();
        btnMesa2 = new javax.swing.JButton();
        btnMesa3 = new javax.swing.JButton();
        btnMesa4 = new javax.swing.JButton();
        btnMesa5 = new javax.swing.JButton();
        btnMesa6 = new javax.swing.JButton();
        btnMesa7 = new javax.swing.JButton();
        btnMesa8 = new javax.swing.JButton();
        btnMesa9 = new javax.swing.JButton();
        btnMesa10 = new javax.swing.JButton();
        btnMesa11 = new javax.swing.JButton();
        btnMesa12 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mDisponible = new javax.swing.JButton();
        mOcupada = new javax.swing.JButton();
        jPanelMostrarMesa = new javax.swing.JPanel();
        panelMesa1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCantidadPersonasMesa1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productosPedidoMesa1 = new javax.swing.JList<>();
        btnAgregarProductoPedidoMesa1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPedidosMesa1 = new javax.swing.JList<>();
        btnRealizarPedidoMesa1 = new javax.swing.JButton();
        btnTotalCuentaMesa1 = new javax.swing.JButton();
        btnGenerarReciboMesa1 = new javax.swing.JButton();
        btnVerPedidosMesa1 = new javax.swing.JButton();
        btnBorrarPedidoMesa1 = new javax.swing.JButton();
        btnBorrarProductoPedidoMesa1 = new javax.swing.JButton();
        panelMesa2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCantidadPersonasMesa2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        productosPedidoMesa2 = new javax.swing.JList<>();
        btnAgregarProductoPedidoMesa2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaPedidosMesa2 = new javax.swing.JList<>();
        btnRealizarPedidoMesa2 = new javax.swing.JButton();
        btnGenerarReciboMesa2 = new javax.swing.JButton();
        btnTotalCuentaMesa2 = new javax.swing.JButton();
        btnBorrarProductoPedidoMesa2 = new javax.swing.JButton();
        btnBorrarPedidoMesa2 = new javax.swing.JButton();
        btnVerPedidosMesa2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        panelMesa3 = new javax.swing.JPanel();
        panelMesa4 = new javax.swing.JPanel();
        panelMesa5 = new javax.swing.JPanel();
        panelMesa6 = new javax.swing.JPanel();
        panelMesa7 = new javax.swing.JPanel();
        panelMesa8 = new javax.swing.JPanel();
        panelMesa9 = new javax.swing.JPanel();
        panelMesa10 = new javax.swing.JPanel();
        panelMesa11 = new javax.swing.JPanel();
        panelMesa12 = new javax.swing.JPanel();
        panelModProducto = new javax.swing.JPanel();
        panelBuscProducto = new javax.swing.JPanel();
        panelElimProducto = new javax.swing.JPanel();
        panelProducDisponibles = new javax.swing.JPanel();
        panelProducAgotados = new javax.swing.JPanel();
        panelGenerarRecibo = new javax.swing.JPanel();
        panelCargarMesas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarRuta = new javax.swing.JButton();
        txtRutaArchivo = new javax.swing.JTextField();
        btnCargarMesas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEstadoArchivo = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuMesero = new javax.swing.JMenu();
        menItemCargarMesas = new javax.swing.JMenuItem();
        menItemCargarProductos = new javax.swing.JMenuItem();
        menItemCerrarSesion = new javax.swing.JMenuItem();
        menuMesas = new javax.swing.JMenu();
        menItemGestionarMesas = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenu();
        menItemModProducto = new javax.swing.JMenuItem();
        menItemBuscProducto = new javax.swing.JMenuItem();
        menItemElimProducto = new javax.swing.JMenuItem();
        menItemProducDisponibles = new javax.swing.JMenuItem();
        menItemProducDAgotados = new javax.swing.JMenuItem();
        menuRecibo = new javax.swing.JMenu();
        menItemGenerarRecibo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMostrar.setVerifyInputWhenFocusTarget(false);
        jPanelMostrar.setLayout(new java.awt.CardLayout());

        jLabel2.setText("CARGAR PRODUCTOS");

        btnBuscarRutaProductos.setText("Buscar archivo productos.txt");

        jLabel5.setText("Estado del archivo");

        txtRutaPrductos.setEditable(false);

        txtEstadoArchivoProductos.setEditable(false);

        btnCargarProductos.setText("Cargar Productos");
        btnCargarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCargarProductosLayout = new javax.swing.GroupLayout(panelCargarProductos);
        panelCargarProductos.setLayout(panelCargarProductosLayout);
        panelCargarProductosLayout.setHorizontalGroup(
            panelCargarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarProductosLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(panelCargarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCargarProductosLayout.createSequentialGroup()
                        .addGroup(panelCargarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCargarProductosLayout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addComponent(btnCargarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarProductosLayout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(403, 403, 403))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargarProductosLayout.createSequentialGroup()
                        .addGroup(panelCargarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCargarProductosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstadoArchivoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarProductosLayout.createSequentialGroup()
                                .addComponent(btnBuscarRutaProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRutaPrductos, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))))
        );
        panelCargarProductosLayout.setVerticalGroup(
            panelCargarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarProductosLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(panelCargarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarRutaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRutaPrductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panelCargarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstadoArchivoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnCargarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        jPanelMostrar.add(panelCargarProductos, "card3");

        jLabel3.setText("CERRAR SESION");

        jLabel6.setText("Ingresar el código generado");

        btnCerrarSesion.setText("Cerrar sisión");

        jLabel7.setText("Código generado");

        jLabel8.setText("Ingresar código");

        btnComprobarCodigo.setText("Comprobar");

        javax.swing.GroupLayout panelCerrarSesionLayout = new javax.swing.GroupLayout(panelCerrarSesion);
        panelCerrarSesion.setLayout(panelCerrarSesionLayout);
        panelCerrarSesionLayout.setHorizontalGroup(
            panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarSesionLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelCerrarSesionLayout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(69, 69, 69)
                            .addGroup(panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCodigoGenerado, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelCerrarSesionLayout.createSequentialGroup()
                                    .addGroup(panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelCerrarSesionLayout.createSequentialGroup()
                                            .addComponent(txtIngresarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(panelCerrarSesionLayout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(btnComprobarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(178, 178, 178)))
                                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCerrarSesionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308)))
                .addGap(79, 79, 79))
        );
        panelCerrarSesionLayout.setVerticalGroup(
            panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarSesionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCerrarSesionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCerrarSesionLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoGenerado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIngresarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprobarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );

        jPanelMostrar.add(panelCerrarSesion, "card4");

        jLabel9.setText("Gestionar Mesas");

        btnMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        btnMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        btnMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        btnMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        btnMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        btnMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        btnMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        btnMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        btnMesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        btnMesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        btnMesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        btnMesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesaGestionMesas.png"))); // NOI18N

        jLabel10.setText("Ocupada");

        jLabel11.setText("Disponible");

        mDisponible.setEnabled(false);

        mOcupada.setEnabled(false);

        jPanelMostrarMesa.setLayout(new java.awt.CardLayout());

        panelMesa1.setBackground(new java.awt.Color(255, 255, 255));
        panelMesa1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Mesa 1");
        panelMesa1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 58, 57));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cantidad de personas en la mesa");
        panelMesa1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 189, 28));
        panelMesa1.add(txtCantidadPersonasMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 95, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Productos del pedido");
        panelMesa1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, 20));

        productosPedidoMesa1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(productosPedidoMesa1);

        panelMesa1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 151, 170));

        btnAgregarProductoPedidoMesa1.setText("Agregar prodcuto al pedido");
        panelMesa1.add(btnAgregarProductoPedidoMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 180, 30));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Productos de la carta");
        panelMesa1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 159, -1));

        listaPedidosMesa1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaPedidosMesa1);

        panelMesa1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 128, 170));

        btnRealizarPedidoMesa1.setText("Realizar pedido");
        panelMesa1.add(btnRealizarPedidoMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 310, 130, 30));

        btnTotalCuentaMesa1.setText("Total cuenta");
        panelMesa1.add(btnTotalCuentaMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 120, 40));

        btnGenerarReciboMesa1.setText("Generar recibo");
        panelMesa1.add(btnGenerarReciboMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 120, 40));

        btnVerPedidosMesa1.setText("Ver pedidos");
        panelMesa1.add(btnVerPedidosMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 120, 40));

        btnBorrarPedidoMesa1.setText("Borrar pedido");
        panelMesa1.add(btnBorrarPedidoMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 120, 40));

        btnBorrarProductoPedidoMesa1.setText("Borrar producto");
        panelMesa1.add(btnBorrarProductoPedidoMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 120, 40));

        jPanelMostrarMesa.add(panelMesa1, "card2");

        panelMesa2.setBackground(new java.awt.Color(255, 255, 255));
        panelMesa2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Mesa 2");
        panelMesa2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 58, 57));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Cantidad de personas en la mesa");
        panelMesa2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 189, 28));
        panelMesa2.add(txtCantidadPersonasMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 95, -1));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Productos de la carta");
        panelMesa2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 159, -1));

        productosPedidoMesa2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(productosPedidoMesa2);

        panelMesa2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 151, 170));

        btnAgregarProductoPedidoMesa2.setText("Agregar prodcuto al pedido");
        panelMesa2.add(btnAgregarProductoPedidoMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 180, 30));

        listaPedidosMesa2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaPedidosMesa2);

        panelMesa2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 128, 170));

        btnRealizarPedidoMesa2.setText("Realizar pedido");
        panelMesa2.add(btnRealizarPedidoMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 310, 130, 30));

        btnGenerarReciboMesa2.setText("Generar recibo");
        panelMesa2.add(btnGenerarReciboMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 120, 40));

        btnTotalCuentaMesa2.setText("Total cuenta");
        panelMesa2.add(btnTotalCuentaMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 120, 40));

        btnBorrarProductoPedidoMesa2.setText("Borrar producto");
        panelMesa2.add(btnBorrarProductoPedidoMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 120, 40));

        btnBorrarPedidoMesa2.setText("Borrar pedido");
        panelMesa2.add(btnBorrarPedidoMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 120, 40));

        btnVerPedidosMesa2.setText("Ver pedidos");
        panelMesa2.add(btnVerPedidosMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 120, 40));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Productos del pedido");
        panelMesa2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, 20));

        jPanelMostrarMesa.add(panelMesa2, "card3");

        panelMesa3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMesa3Layout = new javax.swing.GroupLayout(panelMesa3);
        panelMesa3.setLayout(panelMesa3Layout);
        panelMesa3Layout.setHorizontalGroup(
            panelMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panelMesa3Layout.setVerticalGroup(
            panelMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanelMostrarMesa.add(panelMesa3, "card4");

        panelMesa4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMesa4Layout = new javax.swing.GroupLayout(panelMesa4);
        panelMesa4.setLayout(panelMesa4Layout);
        panelMesa4Layout.setHorizontalGroup(
            panelMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panelMesa4Layout.setVerticalGroup(
            panelMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanelMostrarMesa.add(panelMesa4, "card5");

        panelMesa5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMesa5Layout = new javax.swing.GroupLayout(panelMesa5);
        panelMesa5.setLayout(panelMesa5Layout);
        panelMesa5Layout.setHorizontalGroup(
            panelMesa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panelMesa5Layout.setVerticalGroup(
            panelMesa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanelMostrarMesa.add(panelMesa5, "card6");

        panelMesa6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMesa6Layout = new javax.swing.GroupLayout(panelMesa6);
        panelMesa6.setLayout(panelMesa6Layout);
        panelMesa6Layout.setHorizontalGroup(
            panelMesa6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panelMesa6Layout.setVerticalGroup(
            panelMesa6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanelMostrarMesa.add(panelMesa6, "card7");

        panelMesa7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMesa7Layout = new javax.swing.GroupLayout(panelMesa7);
        panelMesa7.setLayout(panelMesa7Layout);
        panelMesa7Layout.setHorizontalGroup(
            panelMesa7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panelMesa7Layout.setVerticalGroup(
            panelMesa7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanelMostrarMesa.add(panelMesa7, "card8");

        panelMesa8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMesa8Layout = new javax.swing.GroupLayout(panelMesa8);
        panelMesa8.setLayout(panelMesa8Layout);
        panelMesa8Layout.setHorizontalGroup(
            panelMesa8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panelMesa8Layout.setVerticalGroup(
            panelMesa8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanelMostrarMesa.add(panelMesa8, "card9");

        panelMesa9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMesa9Layout = new javax.swing.GroupLayout(panelMesa9);
        panelMesa9.setLayout(panelMesa9Layout);
        panelMesa9Layout.setHorizontalGroup(
            panelMesa9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panelMesa9Layout.setVerticalGroup(
            panelMesa9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanelMostrarMesa.add(panelMesa9, "card10");

        panelMesa10.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMesa10Layout = new javax.swing.GroupLayout(panelMesa10);
        panelMesa10.setLayout(panelMesa10Layout);
        panelMesa10Layout.setHorizontalGroup(
            panelMesa10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panelMesa10Layout.setVerticalGroup(
            panelMesa10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanelMostrarMesa.add(panelMesa10, "card11");

        panelMesa11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMesa11Layout = new javax.swing.GroupLayout(panelMesa11);
        panelMesa11.setLayout(panelMesa11Layout);
        panelMesa11Layout.setHorizontalGroup(
            panelMesa11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panelMesa11Layout.setVerticalGroup(
            panelMesa11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanelMostrarMesa.add(panelMesa11, "card12");

        panelMesa12.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMesa12Layout = new javax.swing.GroupLayout(panelMesa12);
        panelMesa12.setLayout(panelMesa12Layout);
        panelMesa12Layout.setHorizontalGroup(
            panelMesa12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panelMesa12Layout.setVerticalGroup(
            panelMesa12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanelMostrarMesa.add(panelMesa12, "card13");

        javax.swing.GroupLayout panelGestionarMesasLayout = new javax.swing.GroupLayout(panelGestionarMesas);
        panelGestionarMesas.setLayout(panelGestionarMesasLayout);
        panelGestionarMesasLayout.setHorizontalGroup(
            panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionarMesasLayout.createSequentialGroup()
                .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGestionarMesasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMesa11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelGestionarMesasLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(mOcupada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(mDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMostrarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelGestionarMesasLayout.setVerticalGroup(
            panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionarMesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGestionarMesasLayout.createSequentialGroup()
                        .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGestionarMesasLayout.createSequentialGroup()
                                .addComponent(btnMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelGestionarMesasLayout.createSequentialGroup()
                                .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMesa9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMesa10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGestionarMesasLayout.createSequentialGroup()
                                .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMesa11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMesa8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMesa12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnMesa7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mOcupada, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestionarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestionarMesasLayout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanelMostrarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelMostrar.add(panelGestionarMesas, "card5");

        javax.swing.GroupLayout panelModProductoLayout = new javax.swing.GroupLayout(panelModProducto);
        panelModProducto.setLayout(panelModProductoLayout);
        panelModProductoLayout.setHorizontalGroup(
            panelModProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        panelModProductoLayout.setVerticalGroup(
            panelModProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jPanelMostrar.add(panelModProducto, "card6");

        javax.swing.GroupLayout panelBuscProductoLayout = new javax.swing.GroupLayout(panelBuscProducto);
        panelBuscProducto.setLayout(panelBuscProductoLayout);
        panelBuscProductoLayout.setHorizontalGroup(
            panelBuscProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        panelBuscProductoLayout.setVerticalGroup(
            panelBuscProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jPanelMostrar.add(panelBuscProducto, "card7");

        javax.swing.GroupLayout panelElimProductoLayout = new javax.swing.GroupLayout(panelElimProducto);
        panelElimProducto.setLayout(panelElimProductoLayout);
        panelElimProductoLayout.setHorizontalGroup(
            panelElimProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        panelElimProductoLayout.setVerticalGroup(
            panelElimProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jPanelMostrar.add(panelElimProducto, "card8");

        javax.swing.GroupLayout panelProducDisponiblesLayout = new javax.swing.GroupLayout(panelProducDisponibles);
        panelProducDisponibles.setLayout(panelProducDisponiblesLayout);
        panelProducDisponiblesLayout.setHorizontalGroup(
            panelProducDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        panelProducDisponiblesLayout.setVerticalGroup(
            panelProducDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jPanelMostrar.add(panelProducDisponibles, "card9");

        javax.swing.GroupLayout panelProducAgotadosLayout = new javax.swing.GroupLayout(panelProducAgotados);
        panelProducAgotados.setLayout(panelProducAgotadosLayout);
        panelProducAgotadosLayout.setHorizontalGroup(
            panelProducAgotadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        panelProducAgotadosLayout.setVerticalGroup(
            panelProducAgotadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jPanelMostrar.add(panelProducAgotados, "card10");

        javax.swing.GroupLayout panelGenerarReciboLayout = new javax.swing.GroupLayout(panelGenerarRecibo);
        panelGenerarRecibo.setLayout(panelGenerarReciboLayout);
        panelGenerarReciboLayout.setHorizontalGroup(
            panelGenerarReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        panelGenerarReciboLayout.setVerticalGroup(
            panelGenerarReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jPanelMostrar.add(panelGenerarRecibo, "card11");

        jLabel1.setText("CARGAR MESAS");

        btnBuscarRuta.setText("Buscar archivo mesas.txt");

        txtRutaArchivo.setEditable(false);

        btnCargarMesas.setText("Cargar mesas");

        jLabel4.setText("Estado del archivo");

        txtEstadoArchivo.setEditable(false);

        javax.swing.GroupLayout panelCargarMesasLayout = new javax.swing.GroupLayout(panelCargarMesas);
        panelCargarMesas.setLayout(panelCargarMesasLayout);
        panelCargarMesasLayout.setHorizontalGroup(
            panelCargarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarMesasLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(panelCargarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCargarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargarMesasLayout.createSequentialGroup()
                            .addGroup(panelCargarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBuscarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCargarMesasLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(57, 57, 57)
                            .addGroup(panelCargarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEstadoArchivo)
                                .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargarMesasLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(211, 211, 211)))
                    .addGroup(panelCargarMesasLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnCargarMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(375, 375, 375)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panelCargarMesasLayout.setVerticalGroup(
            panelCargarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarMesasLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelCargarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(panelCargarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnCargarMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanelMostrar.add(panelCargarMesas, "card2");

        menuMesero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesero.png"))); // NOI18N
        menuMesero.setText("Mesero");
        menuMesero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuMesero.setPreferredSize(new java.awt.Dimension(122, 50));

        menItemCargarMesas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menItemCargarMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargarmesas.png"))); // NOI18N
        menItemCargarMesas.setText("Cargar mesas");
        menItemCargarMesas.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemCargarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemCargarMesasActionPerformed(evt);
            }
        });
        menuMesero.add(menItemCargarMesas);

        menItemCargarProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menItemCargarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargarProductos.png"))); // NOI18N
        menItemCargarProductos.setText("Cargar productos");
        menItemCargarProductos.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemCargarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemCargarProductosActionPerformed(evt);
            }
        });
        menuMesero.add(menItemCargarProductos);

        menItemCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menItemCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar sesion.png"))); // NOI18N
        menItemCerrarSesion.setText("Cerrar sesión");
        menItemCerrarSesion.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemCerrarSesionActionPerformed(evt);
            }
        });
        menuMesero.add(menItemCerrarSesion);

        jMenuBar2.add(menuMesero);

        menuMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesa.png"))); // NOI18N
        menuMesas.setText("Mesas");
        menuMesas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuMesas.setPreferredSize(new java.awt.Dimension(122, 50));

        menItemGestionarMesas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menItemGestionarMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gestionarmesa.png"))); // NOI18N
        menItemGestionarMesas.setText("Gestionar mesas");
        menItemGestionarMesas.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemGestionarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemGestionarMesasActionPerformed(evt);
            }
        });
        menuMesas.add(menItemGestionarMesas);

        jMenuBar2.add(menuMesas);

        menuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N
        menuProductos.setText("Productos");
        menuProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuProductos.setPreferredSize(new java.awt.Dimension(122, 50));

        menItemModProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menItemModProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificarproducto.png"))); // NOI18N
        menItemModProducto.setText("Modificar producto");
        menItemModProducto.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemModProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemModProductoActionPerformed(evt);
            }
        });
        menuProductos.add(menItemModProducto);

        menItemBuscProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menItemBuscProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar producto.png"))); // NOI18N
        menItemBuscProducto.setText("BuscarProducto");
        menItemBuscProducto.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemBuscProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemBuscProductoActionPerformed(evt);
            }
        });
        menuProductos.add(menItemBuscProducto);

        menItemElimProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menItemElimProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarProducto.png"))); // NOI18N
        menItemElimProducto.setText("Eliminar producto");
        menItemElimProducto.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemElimProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemElimProductoActionPerformed(evt);
            }
        });
        menuProductos.add(menItemElimProducto);

        menItemProducDisponibles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menItemProducDisponibles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productosDisponibles.png"))); // NOI18N
        menItemProducDisponibles.setText("Productos disponibles");
        menItemProducDisponibles.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemProducDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemProducDisponiblesActionPerformed(evt);
            }
        });
        menuProductos.add(menItemProducDisponibles);

        menItemProducDAgotados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menItemProducDAgotados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productoAgotado.png"))); // NOI18N
        menItemProducDAgotados.setText("Productos agotados");
        menItemProducDAgotados.setPreferredSize(new java.awt.Dimension(180, 40));
        menItemProducDAgotados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemProducDAgotadosActionPerformed(evt);
            }
        });
        menuProductos.add(menItemProducDAgotados);

        jMenuBar2.add(menuProductos);

        menuRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recibo.png"))); // NOI18N
        menuRecibo.setText("Recibo");
        menuRecibo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuRecibo.setPreferredSize(new java.awt.Dimension(180, 40));

        menItemGenerarRecibo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menItemGenerarRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/generarRecibo.png"))); // NOI18N
        menItemGenerarRecibo.setText("Generar recibo");
        menItemGenerarRecibo.setPreferredSize(new java.awt.Dimension(180, 30));
        menItemGenerarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemGenerarReciboActionPerformed(evt);
            }
        });
        menuRecibo.add(menItemGenerarRecibo);

        jMenuBar2.add(menuRecibo);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menItemProducDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemProducDisponiblesActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrar.getLayout();
        layout.show(jPanelMostrar, "panelProducDisponibles");
    }//GEN-LAST:event_menItemProducDisponiblesActionPerformed

    private void menItemCargarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemCargarMesasActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrar.getLayout();
        layout.show(jPanelMostrar, "panelCargarMesas");
    }//GEN-LAST:event_menItemCargarMesasActionPerformed

    private void menItemCargarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemCargarProductosActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrar.getLayout();
        layout.show(jPanelMostrar, "panelCargarProductos");
    }//GEN-LAST:event_menItemCargarProductosActionPerformed

    private void menItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemCerrarSesionActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrar.getLayout();
        layout.show(jPanelMostrar, "panelCerrarSesion");
    }//GEN-LAST:event_menItemCerrarSesionActionPerformed

    private void btnCargarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarProductosActionPerformed

    private void menItemGestionarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemGestionarMesasActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrar.getLayout();
        layout.show(jPanelMostrar, "panelGestionarMesas");
    }//GEN-LAST:event_menItemGestionarMesasActionPerformed

    private void menItemModProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemModProductoActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrar.getLayout();
        layout.show(jPanelMostrar, "panelModProducto");
    }//GEN-LAST:event_menItemModProductoActionPerformed

    private void menItemBuscProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemBuscProductoActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrar.getLayout();
        layout.show(jPanelMostrar, "panelBuscProducto");
    }//GEN-LAST:event_menItemBuscProductoActionPerformed

    private void menItemElimProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemElimProductoActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrar.getLayout();
        layout.show(jPanelMostrar, "panelElimProducto");
    }//GEN-LAST:event_menItemElimProductoActionPerformed

    private void menItemProducDAgotadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemProducDAgotadosActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrar.getLayout();
        layout.show(jPanelMostrar, "panelProducAgotados");
    }//GEN-LAST:event_menItemProducDAgotadosActionPerformed

    private void menItemGenerarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemGenerarReciboActionPerformed
        CardLayout layout = (CardLayout) jPanelMostrar.getLayout();
        layout.show(jPanelMostrar, "panelGenerarRecibo");
    }//GEN-LAST:event_menItemGenerarReciboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mesero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProductoPedidoMesa1;
    private javax.swing.JButton btnAgregarProductoPedidoMesa2;
    private javax.swing.JButton btnBorrarPedidoMesa1;
    private javax.swing.JButton btnBorrarPedidoMesa2;
    private javax.swing.JButton btnBorrarProductoPedidoMesa1;
    private javax.swing.JButton btnBorrarProductoPedidoMesa2;
    private javax.swing.JButton btnBuscarRuta;
    private javax.swing.JButton btnBuscarRutaProductos;
    private javax.swing.JButton btnCargarMesas;
    private javax.swing.JButton btnCargarProductos;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnComprobarCodigo;
    private javax.swing.JButton btnGenerarReciboMesa1;
    private javax.swing.JButton btnGenerarReciboMesa2;
    private javax.swing.JButton btnMesa1;
    private javax.swing.JButton btnMesa10;
    private javax.swing.JButton btnMesa11;
    private javax.swing.JButton btnMesa12;
    private javax.swing.JButton btnMesa2;
    private javax.swing.JButton btnMesa3;
    private javax.swing.JButton btnMesa4;
    private javax.swing.JButton btnMesa5;
    private javax.swing.JButton btnMesa6;
    private javax.swing.JButton btnMesa7;
    private javax.swing.JButton btnMesa8;
    private javax.swing.JButton btnMesa9;
    private javax.swing.JButton btnRealizarPedidoMesa1;
    private javax.swing.JButton btnRealizarPedidoMesa2;
    private javax.swing.JButton btnTotalCuentaMesa1;
    private javax.swing.JButton btnTotalCuentaMesa2;
    private javax.swing.JButton btnVerPedidosMesa1;
    private javax.swing.JButton btnVerPedidosMesa2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanelMostrar;
    private javax.swing.JPanel jPanelMostrarMesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listaPedidosMesa1;
    private javax.swing.JList<String> listaPedidosMesa2;
    private javax.swing.JButton mDisponible;
    private javax.swing.JButton mOcupada;
    private javax.swing.JMenuItem menItemBuscProducto;
    private javax.swing.JMenuItem menItemCargarMesas;
    private javax.swing.JMenuItem menItemCargarProductos;
    private javax.swing.JMenuItem menItemCerrarSesion;
    private javax.swing.JMenuItem menItemElimProducto;
    private javax.swing.JMenuItem menItemGenerarRecibo;
    private javax.swing.JMenuItem menItemGestionarMesas;
    private javax.swing.JMenuItem menItemModProducto;
    private javax.swing.JMenuItem menItemProducDAgotados;
    private javax.swing.JMenuItem menItemProducDisponibles;
    private javax.swing.JMenu menuMesas;
    private javax.swing.JMenu menuMesero;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuRecibo;
    private javax.swing.JPanel panelBuscProducto;
    private javax.swing.JPanel panelCargarMesas;
    private javax.swing.JPanel panelCargarProductos;
    private javax.swing.JPanel panelCerrarSesion;
    private javax.swing.JPanel panelElimProducto;
    private javax.swing.JPanel panelGenerarRecibo;
    private javax.swing.JPanel panelGestionarMesas;
    private javax.swing.JPanel panelMesa1;
    private javax.swing.JPanel panelMesa10;
    private javax.swing.JPanel panelMesa11;
    private javax.swing.JPanel panelMesa12;
    private javax.swing.JPanel panelMesa2;
    private javax.swing.JPanel panelMesa3;
    private javax.swing.JPanel panelMesa4;
    private javax.swing.JPanel panelMesa5;
    private javax.swing.JPanel panelMesa6;
    private javax.swing.JPanel panelMesa7;
    private javax.swing.JPanel panelMesa8;
    private javax.swing.JPanel panelMesa9;
    private javax.swing.JPanel panelModProducto;
    private javax.swing.JPanel panelProducAgotados;
    private javax.swing.JPanel panelProducDisponibles;
    private javax.swing.JList<String> productosPedidoMesa1;
    private javax.swing.JList<String> productosPedidoMesa2;
    private javax.swing.JTextField txtCantidadPersonasMesa1;
    private javax.swing.JTextField txtCantidadPersonasMesa2;
    private javax.swing.JTextField txtCodigoGenerado;
    private javax.swing.JTextField txtEstadoArchivo;
    private javax.swing.JTextField txtEstadoArchivoProductos;
    private javax.swing.JTextField txtIngresarCodigo;
    private javax.swing.JTextField txtRutaArchivo;
    private javax.swing.JTextField txtRutaPrductos;
    // End of variables declaration//GEN-END:variables
}
