/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import clases.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author EQUIPO
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        btnRegistrarsse = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();
        txtRegistrarNombreUsuario = new javax.swing.JTextField();
        btnVolverAtras = new javax.swing.JButton();
        txtRegistrarContrasenia = new javax.swing.JPasswordField();
        txtRegistrarConfirmarContrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel72.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 0, 0));
        jLabel72.setText("REGISTRATE");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 170, 40));

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(0, 0, 0));
        jLabel74.setText("Ingresa tus datos");
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, 30));

        jLabel75.setForeground(new java.awt.Color(0, 0, 0));
        jLabel75.setText("Nombre de usaurio");
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 146, 40));

        jLabel76.setForeground(new java.awt.Color(0, 0, 0));
        jLabel76.setText("Confirmar contraseña");
        jPanel1.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 146, 40));

        btnRegistrarsse.setBackground(new java.awt.Color(153, 153, 0));
        btnRegistrarsse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarsse.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarsse.setText("Registrarme");
        btnRegistrarsse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarsseActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarsse, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 160, 100));

        jLabel77.setForeground(new java.awt.Color(0, 0, 0));
        jLabel77.setText("Contraseña");
        jPanel1.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 243, 146, 40));
        jPanel1.add(txtRegistrarNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 160, -1));

        btnVolverAtras.setBackground(new java.awt.Color(153, 153, 0));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolverAtras.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverAtras.setText("Volver atrás");
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 160, 40));
        jPanel1.add(txtRegistrarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 160, -1));
        jPanel1.add(txtRegistrarConfirmarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        
        new BievenidaO().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void btnRegistrarsseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarsseActionPerformed
        String nombreUsuario = txtRegistrarNombreUsuario.getText().trim();
        String contrasenia = new String(txtRegistrarContrasenia.getPassword()).trim();
        String confirmarContrasenia = new String(txtRegistrarConfirmarContrasenia.getPassword()).trim();

        if (nombreUsuario.isEmpty() || contrasenia.isEmpty() || confirmarContrasenia.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, complete todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!contrasenia.equals(confirmarContrasenia)) {
            JOptionPane.showMessageDialog(rootPane, "Las contraseñas no coinciden.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Object[] opciones = {"Mesero", "Administrador"};
        int seleccion = JOptionPane.showOptionDialog(this, "Seleccione el tipo de usuario:", "Tipo de Usuario",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

        Usuario nuevoUsuario;
        if (seleccion == 0) {
            nuevoUsuario = new Mesero(nombreUsuario, contrasenia);
        } else if (seleccion == 1) {
            nuevoUsuario = new Administrador(nombreUsuario, contrasenia);
        } else {
            JOptionPane.showMessageDialog(this, "No se seleccionó ningún tipo de usuario.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Aquí se debe agregar el usuario a una lista o base de datos global
        listaUsuarios.add(nuevoUsuario); // listaUsuarios es una lista global que contiene los usuarios

        JOptionPane.showMessageDialog(this, "Usuario registrado con éxito.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        limpiarCamposRegistro();
    }//GEN-LAST:event_btnRegistrarsseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarsse;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtRegistrarConfirmarContrasenia;
    private javax.swing.JPasswordField txtRegistrarContrasenia;
    private javax.swing.JTextField txtRegistrarNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
